# Generated by Django 3.2.12 on 2023-06-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxfiling',
            name='filing_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
