# Generated by Django 3.2.12 on 2023-06-12 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Miss', 'Miss')], max_length=5)),
                ('maiden_name', models.CharField(blank=True, max_length=20)),
                ('postal_address', models.TextField(blank=True, max_length=100)),
                ('physical_address', models.TextField(blank=True, max_length=100)),
                ('village_suburb', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('home_phone_number', models.CharField(blank=True, max_length=15)),
                ('office_phone_number', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('other_email', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('tin', models.CharField(blank=True, max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('birth_contry', models.CharField(blank=True, max_length=20)),
                ('residence_country', models.CharField(blank=True, max_length=20)),
                ('citizenship_country', models.CharField(blank=True, max_length=20)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced'), ('widowed', 'widowed')], max_length=10)),
                ('spouse_name', models.CharField(blank=True, max_length=50, null=True)),
                ('spouse_tin', models.CharField(blank=True, max_length=15, null=True)),
                ('marriage_type', models.CharField(blank=True, choices=[('incommunity', 'incommunity'), ('antenuptial', 'antenuptial'), ('other', 'other')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('document_number', models.CharField(blank=True, max_length=20)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to=users.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
