# Generated by Django 3.2.12 on 2023-06-12 16:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_bankdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankDetails',
            new_name='BankDetail',
        ),
    ]
